# Generated by Django 4.0.1 on 2022-01-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memories", "0003_usersocialmetadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersocialmetadata",
            name="full_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
